name: main-reusable

on:
  workflow_dispatch:

jobs:
  run_main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fs_type: ['ext2', 'ext4', 'xfs', 'btrfs']
        config: ['1k_quick', '4k_quick', '1k_auto', '4k_auto']
    steps:
    - name: Checkout
      uses: actions/checkout@v3
#    - name: reusable
#      uses: riteshharjani/github-actions/.github/workflows/ghactions-reusable.yml@master
#      with:
#        fs_type: ${{ matrix.fs_type }}
#        config: ${{ matrix.config }}
