name: main-reusable

permissions:
  contents: read
  checks: write
  id-token: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      wd_all:
        description: 'Run for all filesystems'
        required: true
        default: false
      wd_ext2:
        description: 'Run ext2 filesystems'
        required: true
        default: false
      wd_ext4:
        description: 'Run ext4 filesystems'
        required: true
        default: true
      wd_xfs:
        description: 'Run xfs filesystems'
        required: true
        default: false
      wd_btrfs:
        description: 'Run btrfs filesystems'
        required: true
        default: false
      wd_config:
        description: 'quick or auto'
        required: true
        default: 'quick'
      wd_repo:
        description: 'linux repo and branch to run'
        required: true
        default: 'riteshharjani/linux'
      wd_branch:
        description: 'linux branch for this repo'
        required: true
        default: 'master'

jobs:
  build_kernel:
    runs-on: self-hosted
    steps:
    - name: Checkout "${{ github.event.inputs.wd_repo }} @ ${{ github.event.inputs.wd_branch }}" repository
      uses: actions/checkout@v3
      with:
        repository: ${{ github.event.inputs.wd_repo }}
        ref:  ${{ github.event.inputs.wd_branch }}
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y gcc
        sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev bc libelf-dev fakeroot dkms ccache
    - name: Compile Linux
      run: |
        make defconfig
        wget https://raw.githubusercontent.com/tytso/xfstests-bld/master/kernel-build/kernel-configs/perf-config-6.1 -O myconfig
        cat myconfig >> .config
        make olddefconfig
        make CC="ccache gcc" -j$(nproc) Werror=1
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: kernel_artifacts
        path: |
          arch/x86/boot/bzImage
          arch/x86/boot/.config
          System.map
          vmlinux
  call-reusable-workflow-ext2:
    uses: riteshharjani/github-actions/.github/workflows/ghactions-reusable.yml@master
    if: ${{ github.event.inputs.wd_ext2 == 'true' || github.event.inputs.wd_all == 'true' }}
    with:
      fs_type: "ext2"
      config: ${{ github.event.inputs.config }}
      repo: ${{ github.event.inputs.wd_repo }}
      branch: ${{ github.event.inputs.wd_branch }}
  call-reusable-workflow-ext4:
    uses: riteshharjani/github-actions/.github/workflows/ghactions-reusable.yml@master
    if: ${{ github.event.inputs.wd_ext4 == 'true' || github.event.inputs.wd_all == 'true' }}
    with:
      fs_type: "ext4"
      config: ${{ github.event.inputs.config }}
      repo: ${{ github.event.inputs.wd_repo }}
      branch: ${{ github.event.inputs.wd_branch }}
  call-reusable-workflow-xfs:
    uses: riteshharjani/github-actions/.github/workflows/ghactions-reusable.yml@master
    if: ${{ github.event.inputs.wd_xfs == 'true' || github.event.inputs.wd_all == 'true' }}
    with:
      fs_type: "xfs"
      config: ${{ github.event.inputs.config }}
      repo: ${{ github.event.inputs.wd_repo }}
      branch: ${{ github.event.inputs.wd_branch }}
  call-reusable-workflow-btrfs:
    uses: riteshharjani/github-actions/.github/workflows/ghactions-reusable.yml@master
    if: ${{ github.event.inputs.wd_btrfs == 'true' || github.event.inputs.wd_all == 'true' }}
    with:
      fs_type: "btrfs"
      config: ${{ github.event.inputs.config }}
      repo: ${{ github.event.inputs.wd_repo }}
      branch: ${{ github.event.inputs.wd_branch }}
  call-reusable-workflow-fstests-ext4:
    needs: build_kernel
    uses: riteshharjani/github-actions/.github/workflows/ghaction-xfstests-2.yml@master
    if: ${{ github.event.inputs.wd_ext4 == 'true' || github.event.inputs.wd_all == 'true' }}
    with:
      fs_type: "ext4"
      config: ${{ github.event.inputs.config }}
      repo: ${{ github.event.inputs.wd_repo }}
      branch: ${{ github.event.inputs.wd_branch }}

