name: ghactions

on:
  workflow_dispatch:
    inputs:
      wd_all:
        description: 'Run for all filesystems'
        required: true
        default: false
      wd_ext2:
        description: 'Run ext2 filesystems'
        required: true
        default: false
      wd_ext4:
        description: 'Run ext4 filesystems'
        required: true
        default: false
      wd_xfs:
        description: 'Run xfs filesystems'
        required: true
        default: false
      wd_btrfs:
        description: 'Run btrfs filesystems'
        required: true
        default: false
      config:
        description: 'auto or quick (default quick)'
        required: true
        default: 'quick'



jobs:
  ghactions:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        fs_type: ['ext2', 'ext4', 'xfs', 'btrfs']
        config: ['1k', '4k', '1k_auto', '4k_auto']

    env:
        FS_TYPE: ${{ matrix.fs_type }}
        CONFIG: ${{ matrix.config }}

    steps:
    - name: Run test
      if: ${{ github.event.inputs.wd_all == 'true' ||
              (matrix.fs_type == 'ext2' && github.event.inputs.wd_ext2 == 'true') ||
              (matrix.fs_type == 'ext4' && github.event.inputs.wd_ext4 == 'true') ||
              (matrix.fs_type == 'xfs' && github.event.inputs.wd_xfs == 'true') ||
              (matrix.fs_type == 'btrfs' && github.event.inputs.wd_btrfs == 'true') ||
              (github.event.inputs.config == 'auto' && endsWith(matrix.config, '_auto')) ||
              (github.event.inputs.config == 'quick' && !endsWith(matrix.config, '_auto'))
            }}
      run: |
          echo "Test running for ${{ matrix.fs_type }} with ${{ matrix.config }}"

