name: main-reusable

on:
  workflow_dispatch:
    inputs:
      wd_all:
        description: 'Run for all filesystems'
        required: true
        default: false
      wd_ext2:
        description: 'Run ext2 filesystems'
        required: true
        default: false
      wd_ext4:
        description: 'Run ext4 filesystems'
        required: true
        default: true
      wd_xfs:
        description: 'Run xfs filesystems'
        required: true
        default: false
      wd_btrfs:
        description: 'Run btrfs filesystems'
        required: true
        default: false
      wd_config:
        description: 'quick or auto'
        required: true
        default: 'quick'
      wd_repo:
        description: 'linux repo and branch to run'
        required: true
        default: 'riteshharjani/linux'
      wd_branch:
        description: 'linux branch for this repo'
        required: true
        default: 'master'

jobs:
  call-reusable-workflow-ext2:
    uses: riteshharjani/github-actions/.github/workflows/ghactions-reusable.yml@master
    if: ${{ github.event.inputs.wd_ext2 == 'true' || github.event.inputs.wd_all == 'true' }}
    with:
      fs_type: "ext2"
      config: ${{ github.event.inputs.config }}
      repo: ${{ github.event.inputs.wd_repo }}
      branch: ${{ github.event.inputs.wd_branch }}
  call-reusable-workflow-ext4:
    uses: riteshharjani/github-actions/.github/workflows/ghactions-reusable.yml@master
    if: ${{ github.event.inputs.wd_ext4 == 'true' || github.event.inputs.wd_all == 'true' }}
    with:
      fs_type: "ext4"
      config: ${{ github.event.inputs.config }}
      repo: ${{ github.event.inputs.wd_repo }}
      branch: ${{ github.event.inputs.wd_branch }}
  call-reusable-workflow-xfs:
    uses: riteshharjani/github-actions/.github/workflows/ghactions-reusable.yml@master
    if: ${{ github.event.inputs.wd_xfs == 'true' || github.event.inputs.wd_all == 'true' }}
    with:
      fs_type: "xfs"
      config: ${{ github.event.inputs.config }}
      repo: ${{ github.event.inputs.wd_repo }}
      branch: ${{ github.event.inputs.wd_branch }}
  call-reusable-workflow-btrfs:
    uses: riteshharjani/github-actions/.github/workflows/ghactions-reusable.yml@master
    if: ${{ github.event.inputs.wd_btrfs == 'true' || github.event.inputs.wd_all == 'true' }}
    with:
      fs_type: "btrfs"
      config: ${{ github.event.inputs.config }}
      repo: ${{ github.event.inputs.wd_repo }}
      branch: ${{ github.event.inputs.wd_branch }}
