name: main-reusable-xfstests

permissions:
  contents: read
  checks: write
  id-token: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      wd_all:
        description: 'Run for all filesystems'
        required: true
        default: false
      wd_ext2:
        description: 'Run ext2 filesystems'
        required: true
        default: false
      wd_ext4:
        description: 'Run ext4 filesystems'
        required: true
        default: true
      wd_xfs:
        description: 'Run xfs filesystems'
        required: true
        default: false
      wd_btrfs:
        description: 'Run btrfs filesystems'
        required: true
        default: false
      wd_repo:
        description: 'linux repo and branch to run'
        required: true
        default: 'riteshharjani/linux'
      wd_branch:
        description: 'linux branch for this repo'
        required: true
        default: 'master'
      wd_configs:
        description: "'1k_quick', '1k_auto', comma seperated array configs"
        required: true
        default: "['1k_auto', '4k_auto']"
      wd_giturl:
        description: "https://git.kernel.org/pub/scm/linux/kernel/git/   or default is github"
        required: true
        default: 'https://github.com/'

jobs:
  build_kernel:
    runs-on: self-hosted
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3
    - name: Checkout "${{ github.event.inputs.wd_repo }} @ ${{ github.event.inputs.wd_branch }}" repository
      if: ${{ github.event.inputs.wd_giturl == 'https://github.com/' }}
      uses: actions/checkout@v3
      with:
        repository: ${{ github.event.inputs.wd_repo }}
        github-server-url: ${{ github.event.inputs.wd_giturl }}
        ref:  ${{ github.event.inputs.wd_branch }}
    - name: Checkout "${{ github.event.inputs.wd_branch }} url $${{ github.event.inputs.wd_giturl }}"
      if: ${{ github.event.inputs.wd_giturl != 'https://github.com/' }}
      run: |
        git init
        git remote add origin '${{ github.event.inputs.wd_giturl }}/${{ github.event.inputs.wd_repo }}.git'
        git fetch --depth 1 origin ${{ github.event.inputs.wd_branch }}
        git checkout FETCH_HEAD
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y gcc
        sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev bc libelf-dev fakeroot dkms ccache
    - name: Compile Linux
      run: |
        make defconfig
        wget https://raw.githubusercontent.com/tytso/xfstests-bld/master/kernel-build/kernel-configs/perf-config-6.1 -O myconfig
        cat myconfig >> .config
        make olddefconfig
        make CC="ccache gcc" -j$(nproc) Werror=1
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: kernel_artifacts
        path: |
          arch/x86/boot/bzImage
          arch/x86/boot/.config
          System.map
          vmlinux
  fstests-ext2:
    needs: build_kernel
    strategy:
      matrix:
        configs: ${{ fromJson(inputs.wd_configs) }}
    uses: riteshharjani/github-actions/.github/workflows/ghaction-xfstests-2.yml@master
    if: ${{ github.event.inputs.wd_ext2 == 'true' || github.event.inputs.wd_all == 'true' }}
    with:
      fs_type: "ext2"
      config: ${{ matrix.configs }}
      repo: ${{ github.event.inputs.wd_repo }}
      branch: ${{ github.event.inputs.wd_branch }}
  fstests-ext4:
    needs: build_kernel
    strategy:
      matrix:
        configs: ${{ fromJson(inputs.wd_configs) }}
    uses: riteshharjani/github-actions/.github/workflows/ghaction-xfstests-2.yml@master
    if: ${{ github.event.inputs.wd_ext4 == 'true' || github.event.inputs.wd_all == 'true' }}
    with:
      fs_type: "ext4"
      config: ${{ matrix.configs }}
      repo: ${{ github.event.inputs.wd_repo }}
      branch: ${{ github.event.inputs.wd_branch }}
  fstests-xfs:
    needs: build_kernel
    strategy:
      matrix:
        configs: ${{ fromJson(inputs.wd_configs) }}
    uses: riteshharjani/github-actions/.github/workflows/ghaction-xfstests-2.yml@master
    if: ${{ github.event.inputs.wd_xfs == 'true' || github.event.inputs.wd_all == 'true' }}
    with:
      fs_type: "xfs"
      config: ${{ matrix.configs }}
      repo: ${{ github.event.inputs.wd_repo }}
      branch: ${{ github.event.inputs.wd_branch }}
  fstests-btrfs:
    needs: build_kernel
    strategy:
      matrix:
        configs: ${{ fromJson(inputs.wd_configs) }}
    uses: riteshharjani/github-actions/.github/workflows/ghaction-xfstests-2.yml@master
    if: ${{ github.event.inputs.wd_btrfs == 'true' || github.event.inputs.wd_all == 'true' }}
    with:
      fs_type: "btrfs"
      config: ${{ matrix.configs }}
      repo: ${{ github.event.inputs.wd_repo }}
      branch: ${{ github.event.inputs.wd_branch }}

