name: ghactions

on:
  workflow_dispatch:

# Define a reusable job template
jobs:
  ext_job_template:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run script
      run: |
        echo "FS_TYPE=${{ env.FS_TYPE }}"

# Define jobs that use the job template
jobs:
  ext2:
    runs-on: ubuntu-latest
    needs: [input_event]
    steps:
    - name: Execute ext2
      env:
        FS_TYPE: ext2
      job: ext_job_template
  ext4:
    runs-on: ubuntu-latest
    needs: [input_event]
    steps:
    - name: Execute ext4
      env:
        FS_TYPE: ext4
      job: ext_job_template

# Define the input_event job
jobs:
  input_event:
    runs-on: ubuntu-latest
    outputs:
      input_data: ${{ steps.input_data.outputs.data }}
    steps:
    - name: Generate input data
      id: input_data
      run: |
        echo "data=example_data" > input_data.txt
    - name: Upload input data
      uses: actions/upload-artifact@v2
      with:
        name: input_data
        path: input_data.txt
