name: ghactions

on:
  workflow_dispatch:
    inputs:
      wd_all:
        description: 'Run for all filesystems'
        required: true
        default: false
      wd_ext2:
        description: 'Run ext2 filesystems'
        required: true
        default: false
      wd_ext4:
        description: 'Run ext4 filesystems'
        required: true
        default: false
      wd_xfs:
        description: 'Run xfs filesystems'
        required: true
        default: false
      wd_btrfs:
        description: 'Run btrfs filesystems'
        required: true
        default: false
      config:
        description: 'auto or quick (default quick)'
        required: true
        default: 'quick'

# Define a reusable job template
jobs:
  ext_job_template:
    runs-on: ubuntu-latest
    steps:
    - name: Run script
      run: |
          echo "running ext_job_template for ${{ env.FS_TYPE }} with ${{ matrix.config }} "

jobs:
  ext2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: ['1k', '4k']
    env:
      FS_TYPE: 'ext2'
    steps:
    - name: Run test
      job: ext_job_template

