name: ghactions xfstests

on:
  workflow_dispatch:
    inputs:
      wd_all:
        description: 'Run for all filesystems'
        required: true
        default: false
      wd_ext2:
        description: 'Run ext2 filesystems'
        required: true
        default: false
      wd_ext4:
        description: 'Run ext4 filesystems'
        required: true
        default: true
      wd_xfs:
        description: 'Run xfs filesystems'
        required: true
        default: false
      wd_btrfs:
        description: 'Run btrfs filesystems'
        required: true
        default: false
      wd_config:
        description: 'quick or auto'
        required: true
        default: 'quick'
      wd_repo:
        description: 'linux repo and branch to run'
        required: true
        default: 'riteshharjani/linux'
      wd_branch:
        description: 'linux branch for this repo'
        required: true
        default: 'master'

permissions:
  contents: read
  checks: write
  id-token: write
  pull-requests: write

jobs:
#  build_kernel:
#    runs-on: ubuntu-latest
#    runs-on: self-hosted
#    steps:
#    - name: Checkout "${{ github.event.inputs.wd_repo }} @ ${{ github.event.inputs.wd_branch }}" repository
#      run: echo "checkout repo ${{ github.event.inputs.wd_repo }}"
#      uses: actions/checkout@v3
#      with:
#        repo: ${{ github.event.inputs.wd_repo }}
#        ref:  ${{ github.event.inputs.wd_branch }}
#    - name: Install dependencies
#      run: |
#        sudo apt-get update && sudo apt-get install -y gcc
#        sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev bc libelf-dev fakeroot dkms ccache
#    - name: Compile Linux
#      run: |
#        make defconfig
#        # by default x86_64_defconfig does not have many FS options enabled.
#        wget https://raw.githubusercontent.com/tytso/xfstests-bld/master/kernel-build/kernel-configs/perf-config-6.1 -O myconfig
#        cat myconfig >> .config
#        make olddefconfig
#        make CC="ccache gcc" -j$(nproc) Werror=1
#    - name: Upload artifacts
#      uses: actions/upload-artifact@v3
#      with:
#        name: kernel_artifacts
#        path: |
#          arch/x86/boot/bzImage
#          arch/x86/boot/.config
#          System.map
#          vmlinux
  ghactions:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        fs_type: ['ext2', 'ext4', 'xfs', 'btrfs']
        config: ['1k_quick', '4k_quick', '1k_auto', '4k_auto']

    env:
        FS_TYPE: ${{ matrix.fs_type }}
        CONFIG: ${{ matrix.config }}

    steps:
    - name: Set environment IS_SKIPPED
      id: set_variable
      run: |
        if (${{ endsWith(matrix.config, github.event.inputs.wd_config) &&
              (github.event.inputs.wd_all == 'true' ||
              (matrix.fs_type == 'ext2' && github.event.inputs.wd_ext2 == 'true') ||
              (matrix.fs_type == 'ext4' && github.event.inputs.wd_ext4 == 'true') ||
              (matrix.fs_type == 'xfs' && github.event.inputs.wd_xfs == 'true') ||
              (matrix.fs_type == 'btrfs' && github.event.inputs.wd_btrfs == 'true')
            )}}); then
            echo 'IS_SKIPPED=true' >> $GITHUB_ENV
        else
            echo 'IS_SKIPPED=false' >> $GITHUB_ENV
        fi
    - name: Checkout "${{ github.event.inputs.wd_repo }} @ ${{ github.event.inputs.wd_branch }}" repository
      if: ${{ endsWith(matrix.config, github.event.inputs.wd_config) &&
              (github.event.inputs.wd_all == 'true' ||
              (matrix.fs_type == 'ext2' && github.event.inputs.wd_ext2 == 'true') ||
              (matrix.fs_type == 'ext4' && github.event.inputs.wd_ext4 == 'true') ||
              (matrix.fs_type == 'xfs' && github.event.inputs.wd_xfs == 'true') ||
              (matrix.fs_type == 'btrfs' && github.event.inputs.wd_btrfs == 'true')
            )}}
      uses: actions/checkout@v3
      with:
        repo: ${{ github.event.inputs.wd_repo }}
        ref:  ${{ github.event.inputs.wd_branch }}
    - name: Checkout this repository
      if: ${{ endsWith(matrix.config, github.event.inputs.wd_config) &&
              (github.event.inputs.wd_all == 'true' ||
              (matrix.fs_type == 'ext2' && github.event.inputs.wd_ext2 == 'true') ||
              (matrix.fs_type == 'ext4' && github.event.inputs.wd_ext4 == 'true') ||
              (matrix.fs_type == 'xfs' && github.event.inputs.wd_xfs == 'true') ||
              (matrix.fs_type == 'btrfs' && github.event.inputs.wd_btrfs == 'true')
            )}}
      uses: actions/checkout@v3
    - name: Run test for ${{ matrix.fs_type}} ${{ matrix.config }}
      if: ${{ endsWith(matrix.config, github.event.inputs.wd_config) &&
              (github.event.inputs.wd_all == 'true' ||
              (matrix.fs_type == 'ext2' && github.event.inputs.wd_ext2 == 'true') ||
              (matrix.fs_type == 'ext4' && github.event.inputs.wd_ext4 == 'true') ||
              (matrix.fs_type == 'xfs' && github.event.inputs.wd_xfs == 'true') ||
              (matrix.fs_type == 'btrfs' && github.event.inputs.wd_btrfs == 'true')
            )}}
      run: |
        sudo FS_TYPE=$FS_TYPE CONFIG=$CONFIG python3 tests/run_qemu_xfstests.py

