name: kernel + qemu + xfstests

on:
  workflow_dispatch:
  push:
      branches:
        - '**'
jobs:
  build_kernel:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y gcc
        sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev bc libelf-dev fakeroot dkms
    - name: Compile Linux
      run: |
        echo "Linux compiled fine"
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: kernel_artifacts
        path: |
          arch/x86/boot/bzImage

  run_qemu:
    needs: build_kernel
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: kernel_artifacts
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y \
        gcc \
        python3 python3-pip \
        qemu-system-x86 \
        qemu-utils cloud-image-utils
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install pexpect
      run: sudo pip3 install pexpect
    - name: Cloud-init image
      run: |
          sudo cloud-localds user-data.img user-data.yaml
#    - name: Create dummy qcow image
#      run: |
#          qemu-img create -f qcow2 jammy-server-cloudimg-amd64.img 20G
    - name: Download Ubuntu cloud image
      run: |
        sudo wget https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
        sudo qemu-img resize jammy-server-cloudimg-amd64.img +20G
    - name: Run expect script
#      continue-on-error: true
      run: |
        pwd
        ls
        mount
        df -h
        cat .github/workflows/expect_script.py
        sudo python3 .github/workflows/expect_script.py
