name: Matrix from input_3

on:

  workflow_dispatch:

    inputs:

      configs:

        description: 'Comma-separated list of configs'

        required: true

        default: "['1k', '4k']"

jobs:


  use_matrix:



    runs-on: ubuntu-latest

    strategy:

      matrix:

        config: ${{fromJson(inputs.config)}}

    steps:

      - name: Show matrix value

        run: echo "Current config value ${{ matrix.config }}"
