name: publish test results

on:
  workflow_dispatch:
      #  push:
      #    branches:
      #      - "**"
permissions:
  contents: read
  checks: write
  id-token: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Update xfstests.global name
      run: find results/ -name "result.xml" -exec sh -c 'parent_dir=$(basename $(dirname {})); sed -i "s/xfstests.global/xfstests-${parent_dir}/g" {}' \;
    - name: Upload xfstests artifacts
      uses: actions/upload-artifact@v2
      with:
        name: xfstests-results
        path: results/
    - name: Publish results
      continue-on-error: true
      uses: mikepenz/action-junit-report@v3
      if: always()
      with:
        commit: ${{ github.sha }}
        detailed_summary: true
        annotate_notice: true
        include_passed: true
        report_paths: 'results/job*/results*/result.xml'
        github_token: ${{ secrets.GITHUB_TOKEN }}
