name: publish test results

on:
    workflow_dispatch:
    push:
        branches:
            - "**"
jobs:
    build:
        runs-on: ubuntu-latest
        steps:

        - name: Do nothing
          run: echo "Do nothing"

        - name: Publish results
          uses: EnricoMi/publish-unit-test-result-action@v2
          if: always()
          with:
              files: |
                  results/**/*.xml
                  results/**/*.json
