name: publish test results

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
permissions:
  contents: read
  checks: write
  id-token: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Do nothing
      run: echo "Do nothing"
    - name: Upload xfstests artifacts
      uses: actions/upload-artifact@v2
      with:
        name: xfstests-results
        path: results/
    - name: Publish results
      continue-on-error: true
      uses: mikepenz/action-junit-report@v3
      if: always()
      with:
        name: xfstests-results
        report_paths: 'results/job*/results*/result.xml'
        github_token: ${{ secrets.GITHUB_TOKEN }}
