name: publish test results

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Do nothing
      run: echo "Do nothing"

    - name: Upload xfstests artifacts
      uses: actions/upload-artifact@v2
      with:
        name: xfstests-results
        path: results/
    - name: Publish results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: xfstests-results
        path: 'results/job*/results*/result.xml'
#    - name: Publish results
#      uses: EnricoMi/publish-unit-test-result-action@v2
#      if: always()
#      with:
#        files: |
#          results/job*/results*/result.xml

